<?php include __DIR__ . '/includes/header.php'; ?>
<title>Plans & Rewards · TrainTote Ops Manager</title></head><body><main class="container py-5">
<section class="text-center mb-5"><h1 class="display-5 fw-bold">TrainTote Ops, your way</h1><p class="lead text-muted">Start free, choose a plan, or earn access with TrainTote packs.</p></section>
<div class="row row-cols-1 row-cols-lg-3 g-4 justify-content-center">
<div class="col"><div class="card h-100"><div class="card-body p-4"><h2 class="h3">Free</h2><p class="fs-2 fw-bold">$0</p><p>Get organized and try TrainTote Ops.</p><ul><li>Equipment roster</li><li>Industries and waybills</li><li>Basic operating sessions</li></ul><a class="btn btn-outline-primary w-100" href="register.php">Create free account</a></div></div></div>
<div class="col"><div class="card h-100 border-primary"><div class="card-body p-4"><h2 class="h3">Plus</h2><p class="fs-2 fw-bold">$3.99 <small class="fs-6">/ month</small></p><p>Or <strong>$39.99 / year</strong></p><ul><li>More room for your railroad</li><li>Expanded operations access</li><li>Imports and exports</li></ul><a class="btn btn-primary w-100" href="register.php">Choose Plus</a></div></div></div>
<div class="col"><div class="card h-100 border-primary shadow"><div class="card-body p-4"><span class="badge text-bg-primary mb-2">Best value</span><h2 class="h3">Pro</h2><p class="fs-2 fw-bold">$8.99 <small class="fs-6">/ month</small></p><p>Or <strong>$89.99 / year</strong></p><ul><li>Everything in Plus</li><li>Photo and AI equipment tools</li><li>Advanced session tools</li></ul><a class="btn btn-primary w-100" href="register.php">Choose Pro</a></div></div></div>
</div>
<section class="card mt-5"><div class="card-body p-4"><h2 class="h3">Earn access with TrainTote packs</h2><div class="row"><div class="col-md-6"><h3 class="h5">Buy any qualifying 5-pack</h3><p>Receive <strong>90 days of Plus</strong>.</p></div><div class="col-md-6"><h3 class="h5">Spend $100 or more in one order</h3><p>Receive <strong>one full year of Pro</strong>, including the Large Tall 5-pack.</p></div></div><a class="btn btn-outline-primary" href="https://traintote.com/product-category/packs/">Shop TrainTote packs</a><p class="small text-muted mt-3 mb-0">Completed qualifying orders only; shipping and tax excluded. The best reward applies per order. Use the same email for WooCommerce checkout and TrainTote Ops.</p></div></section><p class="text-center mt-4"><a href="login.php">Already have an account? Log in</a></p></main><?php include __DIR__ . '/includes/footer.php'; ?>
