<?php
session_start();
require_once '../config/database.php';
require_once 'lib.php';
require_once 'generator.php';
if(!isset($_SESSION['user_id'])){header('Location: ../login.php');exit;}
$railroad=ttOperationsRailroad($pdo,(int)$_SESSION['user_id']);$railroadId=(int)$railroad['id'];$assignmentId=(int)($_GET['assignment_id']??$_POST['assignment_id']??0);
if($assignmentId<=0){header('Location: sessions.php');exit;}
$stmt=$pdo->prepare('SELECT a.*,s.session_number,s.session_name FROM operation_assignments a JOIN operating_sessions s ON s.id=a.session_id WHERE a.id=? AND a.railroad_id=?');$stmt->execute([$assignmentId,$railroadId]);$assignment=$stmt->fetch(PDO::FETCH_ASSOC);
if(!$assignment){http_response_code(404);die('Assignment not found.');}$error='';

$routeStmt=$pdo->prepare("SELECT jrs.*,COALESCE(jop.work_scope,'entire_railroad') work_scope FROM jobs j LEFT JOIN job_operation_profiles jop ON jop.job_id=j.id AND jop.railroad_id=j.railroad_id LEFT JOIN job_route_stops jrs ON jrs.job_id=j.id AND jrs.railroad_id=j.railroad_id WHERE j.id=? AND j.railroad_id=? ORDER BY jrs.sequence_number");
$routeStmt->execute([(int)$assignment['job_template_id'],$railroadId]);$routeRows=$routeStmt->fetchAll(PDO::FETCH_ASSOC);$routeStops=array_values(array_filter($routeRows,static fn($row)=>(int)($row['id']??0)>0));$assignment['work_scope']=$routeRows[0]['work_scope']??'entire_railroad';
$selectedRouteMissingStops=$assignment['work_scope']==='selected_route'&&!$routeStops;

if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        ttOperationsRequireCsrf();
        if($selectedRouteMissingStops)throw new RuntimeException('This Job Title uses Selected Route / Territory but has no route stops. Add at least one stop or change the scope to Entire Railroad.');
        $pdo->beginTransaction();$reserved=ttReservedEquipmentIds($pdo,$railroadId,$assignmentId);
        $startingStmt=$pdo->prepare('SELECT equipment_id FROM operation_assignment_starting_cars WHERE assignment_id=?');$startingStmt->execute([$assignmentId]);$startingIds=array_map('intval',$startingStmt->fetchAll(PDO::FETCH_COLUMN));
        $carsStmt=$pdo->prepare("SELECT e.id,e.reporting_marks,e.road_number,e.equipment_type,e.operations_service,e.load_status,e.current_industry_id,e.current_track,e.photo_filename,i.industry_name origin_name FROM equipment e JOIN industries i ON i.id=e.current_industry_id WHERE e.railroad_id=? AND e.active=1 AND COALESCE(e.equipment_class,'')<>'Locomotive' ORDER BY e.reporting_marks,e.road_number FOR UPDATE");$carsStmt->execute([$railroadId]);$cars=$carsStmt->fetchAll(PDO::FETCH_ASSOC);
        $industriesStmt=$pdo->prepare('SELECT id,industry_name,industry_type,receives_services,ships_services,track_capacity FROM industries WHERE railroad_id=? AND active=1 ORDER BY industry_name');$industriesStmt->execute([$railroadId]);$industries=$industriesStmt->fetchAll(PDO::FETCH_ASSOC);
        $plan=ttChooseOperationsMoves($assignment,$cars,$industries,$startingIds,$reserved,$routeStops);
        $revStmt=$pdo->prepare('SELECT COALESCE(MAX(revision_number),0)+1 FROM operation_switch_lists WHERE assignment_id=? FOR UPDATE');$revStmt->execute([$assignmentId]);$revision=(int)$revStmt->fetchColumn();
        $insert=$pdo->prepare("INSERT INTO operation_switch_lists(railroad_id,session_id,assignment_id,switch_list_number,revision_number,status,generated_by_user_id,planned_move_count,diagnostic_summary) VALUES(?,?,?,?,?,'draft',?,?,?)");$insert->execute([$railroadId,(int)$assignment['session_id'],$assignmentId,$assignment['assignment_number'],$revision,(int)$_SESSION['user_id'],count($plan['moves']),implode("\n",$plan['diagnostics'])]);$listId=(int)$pdo->lastInsertId();
        $moveInsert=$pdo->prepare('INSERT INTO operation_switch_list_moves(switch_list_id,railroad_id,sequence_number,movement_group,equipment_id,reporting_marks_snapshot,road_number_snapshot,equipment_type_snapshot,service_snapshot,photo_filename_snapshot,original_load_status,planned_load_status,origin_industry_id,origin_name_snapshot,origin_track,destination_industry_id,destination_name_snapshot,destination_track,action,instruction,work_location) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$sequence=1;
        if($assignment['start_method']==='prepared_cut')$moveInsert->execute([$listId,$railroadId,$sequence++,'instruction-pickup',null,null,null,null,null,null,null,null,(int)$assignment['operating_base_industry_id'],null,$assignment['starting_track'],null,null,null,'LIGHT ENGINE','Travel light to prepared cut, couple, and perform brake test','Prepared cut pickup']);
        $lastWorkLocation=null;
        foreach($plan['moves']as$move){
            if($move['work_location']!==$lastWorkLocation){$lastWorkLocation=$move['work_location'];$moveInsert->execute([$listId,$railroadId,$sequence++,'location-'.bin2hex(random_bytes(6)),null,null,null,null,null,null,null,null,null,null,null,null,null,null,'LOCATION',strtoupper((string)$lastWorkLocation),(string)$lastWorkLocation]);}
            $moveInsert->execute([$listId,$railroadId,$sequence++,$move['movement_group'],$move['equipment_id'],$move['reporting_marks_snapshot'],$move['road_number_snapshot'],$move['equipment_type_snapshot'],$move['service_snapshot'],$move['photo_filename_snapshot'],$move['original_load_status'],$move['planned_load_status'],$move['origin_industry_id'],$move['origin_name_snapshot'],$move['origin_track'],$move['destination_industry_id'],$move['destination_name_snapshot'],$move['destination_track'],$move['action'],$move['instruction'],$move['work_location']]);
        }
        $pdo->commit();header('Location: work_order.php?id='.$listId);exit;
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}
$latest=$pdo->prepare('SELECT * FROM operation_switch_lists WHERE assignment_id=? AND railroad_id=? ORDER BY revision_number DESC LIMIT 1');$latest->execute([$assignmentId,$railroadId]);$latest=$latest->fetch(PDO::FETCH_ASSOC);
?>
<?php include '../includes/header.php';?><title>Generate <?=ttHtml($assignment['assignment_number'])?></title><link rel="stylesheet" href="../assets/css/operations.css"></head><body><?php include '../includes/navbar.php';?><div class="tt-operations-shell"><?php include '../assets/components/sidebar.php';?><section class="tt-ops-page"><p class="tt-eyebrow"><?=ttHtml($assignment['session_number'].' · '.$assignment['assignment_number'])?></p><h1>Generate Switch List</h1><p class="lead"><?=ttHtml($assignment['title_snapshot'])?></p><?php if($error):?><div class="alert alert-danger"><?=ttHtml($error)?></div><?php endif;?><?php if($selectedRouteMissingStops):?><div class="alert alert-warning">This Job Title uses Selected Route / Territory but has no route stops. Add at least one stop or change the scope to Entire Railroad.</div><?php endif;?><div class="card mb-4"><div class="card-body"><dl class="row"><dt class="col-sm-4">Work scope</dt><dd class="col-sm-8"><?=$assignment['work_scope']==='selected_route'?'Selected Route / Territory':'Entire Railroad'?></dd><dt class="col-sm-4">Operating pattern</dt><dd class="col-sm-8"><?=ttHtml(ttJobTypes()[$assignment['operating_pattern']]??$assignment['operating_pattern'])?></dd><dt class="col-sm-4">Cars to switch</dt><dd class="col-sm-8">Up to <?=(int)$assignment['requested_car_count']?>; invalid work is never invented</dd></dl><?php if($latest):?><p>Latest saved revision: <a href="work_order.php?id=<?=(int)$latest['id']?>"><?=ttHtml($latest['switch_list_number'])?> — Revision <?=(int)$latest['revision_number']?> (<?=ttHtml($latest['status'])?>)</a></p><?php endif;?></div></div><form method="post"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="assignment_id" value="<?=$assignmentId?>"><button class="btn btn-primary" <?=$selectedRouteMissingStops?'disabled':''?>><?php if($latest):?>Regenerate Switch List<?php else:?>Generate Switch List<?php endif;?></button> <a class="btn btn-secondary" href="session_edit.php?id=<?=(int)$assignment['session_id']?>">Back to Session</a> <a class="btn btn-outline-secondary" href="assignment_edit.php?id=<?=$assignmentId?>">Edit Assignment</a><?php if($selectedRouteMissingStops):?> <a class="btn btn-outline-primary" href="../jobs/route.php?id=<?=(int)$assignment['job_template_id']?>">Edit Route</a><?php endif;?></form></section></div><?php include '../includes/footer.php';?>
