<?php
session_start();require_once '../config/database.php';require_once 'lib.php';require_once 'assignment_service.php';
if(!isset($_SESSION['user_id'])){header('Location: ../login.php');exit;}
$railroad=ttOperationsRailroad($pdo,(int)$_SESSION['user_id']);$railroadId=(int)$railroad['id'];$sessionId=(int)($_GET['id']??$_POST['session_id']??0);$error='';
$stmt=$pdo->prepare('SELECT * FROM operating_sessions WHERE id=? AND railroad_id=?');$stmt->execute([$sessionId,$railroadId]);$session=$stmt->fetch(PDO::FETCH_ASSOC);if(!$session){http_response_code(404);die('Operating session not found.');}
if($_SERVER['REQUEST_METHOD']==='POST')try{
    ttOperationsRequireCsrf();$action=(string)($_POST['action']??'');
    if($action==='add_assignment'){
        if(!ttOperatingSessionIsEditable((string)$session['status']))throw new RuntimeException('This operating session is frozen and assignments cannot be created.');$pdo->beginTransaction();$stmt=$pdo->prepare('SELECT status FROM operating_sessions WHERE id=? AND railroad_id=? FOR UPDATE');$stmt->execute([$sessionId,$railroadId]);if(!ttOperatingSessionIsEditable((string)$stmt->fetchColumn()))throw new RuntimeException('This operating session became frozen and the assignment was not created.');$data=ttAssignmentNormalizeInput($pdo,$railroadId,$sessionId,$_POST);$stmt=$pdo->prepare('SELECT COALESCE(MAX(sequence_number),0)+1 FROM operation_assignments WHERE session_id=? FOR UPDATE');$stmt->execute([$sessionId]);$sequence=(int)$stmt->fetchColumn();$job=$data['job'];$number=$session['session_number'].'-'.ttAssignmentSuffix($sequence);$status='draft';
        $stmt=$pdo->prepare('INSERT INTO operation_assignments(railroad_id,session_id,job_template_id,assignment_number,sequence_number,title_snapshot,type_snapshot,description_snapshot,operating_pattern,status,operating_base_industry_id,starting_track,start_method,prepared_cut_id,requested_car_count,prepared_cut_car_count,difficulty,crew_name,predecessor_assignment_id,dependency_mode,end_plan,end_industry_id,end_track,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
        $stmt->execute([$railroadId,$sessionId,$data['job_id'],$number,$sequence,$job['job_name'],$job['job_type'],$job['description'],$data['pattern'],$status,$data['base_id'],$data['starting_track'],$data['start_method'],$data['cut_id'],$data['requested'],$data['prepared_cut_count'],$data['difficulty'],$data['crew'],$data['predecessor'],$data['dependency'],$data['end_plan'],$data['end_id'],$data['end_track'],$data['notes']]);$assignmentId=(int)$pdo->lastInsertId();$reserved=ttReservedEquipmentIds($pdo,$railroadId,$assignmentId);ttAssignmentReplaceLocomotives($pdo,$assignmentId,$railroadId,$data['locomotive_ids'],$reserved);ttAssignmentReplaceStartingCars($pdo,$assignmentId,$railroadId,$data,$reserved);$pdo->commit();header('Location: session_edit.php?id='.$sessionId);exit;
    }
    if($action==='start_session'){
        if(!ttOperatingSessionIsEditable((string)$session['status']))throw new RuntimeException('This operating session cannot be started from its current status.');$stmt=$pdo->prepare("SELECT a.id,a.status,a.predecessor_assignment_id,(SELECT sl.status FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.railroad_id=a.railroad_id ORDER BY sl.revision_number DESC LIMIT 1) latest_list_status FROM operation_assignments a WHERE a.session_id=? AND a.railroad_id=?");$stmt->execute([$sessionId,$railroadId]);[$canStart,$reason]=ttSessionStartReadiness($stmt->fetchAll(PDO::FETCH_ASSOC));if(!$canStart)throw new RuntimeException($reason);$stmt=$pdo->prepare("UPDATE operating_sessions SET status='in_progress',started_at=COALESCE(started_at,NOW()) WHERE id=? AND railroad_id=? AND status IN('draft','ready')");$stmt->execute([$sessionId,$railroadId]);if(!$stmt->rowCount())throw new RuntimeException('This session cannot be started from its current status.');header('Location: session_edit.php?id='.$sessionId);exit;
    }
    throw new RuntimeException('Invalid Session Builder action.');
}catch(Throwable$e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
$jobsStmt=$pdo->prepare('SELECT id,job_name,job_type FROM jobs WHERE railroad_id=? AND active=1 ORDER BY job_name');$jobsStmt->execute([$railroadId]);$jobs=$jobsStmt->fetchAll(PDO::FETCH_ASSOC);
$industriesStmt=$pdo->prepare('SELECT id,industry_name FROM industries WHERE railroad_id=? AND active=1 ORDER BY industry_name');$industriesStmt->execute([$railroadId]);$industries=$industriesStmt->fetchAll(PDO::FETCH_ASSOC);
$locosStmt=$pdo->prepare("SELECT id,reporting_marks,road_number,road_name,current_track FROM equipment WHERE railroad_id=? AND active=1 AND equipment_class='Locomotive' ORDER BY reporting_marks,road_number");$locosStmt->execute([$railroadId]);$locomotives=$locosStmt->fetchAll(PDO::FETCH_ASSOC);
$carsStmt=$pdo->prepare("SELECT e.id,e.reporting_marks,e.road_number,e.equipment_type,e.current_industry_id,e.current_track,i.industry_name FROM equipment e JOIN industries i ON i.id=e.current_industry_id AND i.railroad_id=e.railroad_id WHERE e.railroad_id=? AND e.active=1 AND COALESCE(e.equipment_class,'')<>'Locomotive' AND NOT EXISTS(SELECT 1 FROM operation_assignment_starting_cars ac JOIN operation_assignments a ON a.id=ac.assignment_id WHERE ac.equipment_id=e.id AND a.railroad_id=e.railroad_id AND a.status IN('draft','ready','waiting','in_progress','needs_review')) ORDER BY e.reporting_marks,e.road_number");$carsStmt->execute([$railroadId]);$startingCars=$carsStmt->fetchAll(PDO::FETCH_ASSOC);
$cutsStmt=$pdo->prepare("SELECT c.*,COUNT(pc.equipment_id) car_count,i.industry_name FROM prepared_cuts c JOIN industries i ON i.id=c.current_industry_id AND i.railroad_id=c.railroad_id LEFT JOIN prepared_cut_cars pc ON pc.prepared_cut_id=c.id WHERE c.railroad_id=? AND c.status='ready' AND NOT EXISTS(SELECT 1 FROM prepared_cut_cars pc2 JOIN operation_assignment_starting_cars ac2 ON ac2.equipment_id=pc2.equipment_id JOIN operation_assignments a2 ON a2.id=ac2.assignment_id WHERE pc2.prepared_cut_id=c.id AND a2.railroad_id=c.railroad_id AND a2.status IN('draft','ready','waiting','in_progress','needs_review')) GROUP BY c.id ORDER BY c.cut_number");$cutsStmt->execute([$railroadId]);$cuts=$cutsStmt->fetchAll(PDO::FETCH_ASSOC);
$assignStmt=$pdo->prepare("SELECT a.*,? session_status,i.industry_name base_name,(SELECT COUNT(*) FROM operation_assignment_locomotives al WHERE al.assignment_id=a.id) locomotive_count,(SELECT COUNT(*) FROM operation_assignment_starting_cars ac WHERE ac.assignment_id=a.id) starting_car_count,(SELECT sl.id FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.status<>'cancelled' ORDER BY sl.revision_number DESC LIMIT 1) switch_list_id,(SELECT sl.status FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.status<>'cancelled' ORDER BY sl.revision_number DESC LIMIT 1) switch_list_status,(SELECT sl.status FROM operation_switch_lists sl WHERE sl.assignment_id=a.id ORDER BY sl.revision_number DESC LIMIT 1) latest_list_status,(SELECT sl.planned_move_count FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.status<>'cancelled' ORDER BY sl.revision_number DESC LIMIT 1) planned_move_count,(SELECT COUNT(*) FROM operation_switch_lists sl WHERE sl.assignment_id=a.id AND sl.status IN('approved','in_progress','completed','needs_review')) frozen_list_count FROM operation_assignments a LEFT JOIN industries i ON i.id=a.operating_base_industry_id WHERE a.session_id=? AND a.railroad_id=? ORDER BY a.sequence_number");$assignStmt->execute([(string)$session['status'],$sessionId,$railroadId]);$assignments=$assignStmt->fetchAll(PDO::FETCH_ASSOC);[$canStart,$startReason]=ttSessionStartReadiness($assignments);if(!ttOperatingSessionIsEditable((string)$session['status'])){$canStart=false;$startReason='This operating session is frozen.';}$patterns=ttJobTypes();
?>
<?php include '../includes/header.php';?><title><?=ttHtml($session['session_number'])?> Session Builder</title><link rel="stylesheet" href="../assets/css/operations.css"></head><body><?php include '../includes/navbar.php';?><div class="tt-operations-shell"><?php include '../assets/components/sidebar.php';?><section class="tt-ops-page">
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><p class="tt-eyebrow">Operating Session</p><h1><?=ttHtml($session['session_number'])?><?=$session['session_name']?' — '.ttHtml($session['session_name']):''?></h1><p class="text-muted"><?=ttHtml($session['operating_date'])?> · <span class="badge tt-status-<?=ttHtml($session['status'])?>"><?=ttHtml(ucwords(str_replace('_',' ',$session['status'])))?></span></p></div><div><form method="post"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><input type="hidden" name="action" value="start_session"><button class="btn btn-success" <?=$canStart?'':'disabled'?>>Start Session</button></form><?php if(!$canStart):?><small class="d-block text-muted mt-2" style="max-width:28rem"><?=ttHtml($startReason)?></small><?php endif;?></div></div>
<?php if($error):?><div class="alert alert-danger"><?=ttHtml($error)?></div><?php endif;?>
<div class="tt-assignment-grid mb-4"><?php foreach($assignments as$a):?><?php $retainedStatuses=(int)$a['frozen_list_count']>0?['approved']:array_filter([(string)$a['switch_list_status']]);$legacy=$a['start_method']==='inherit'||!in_array($a['end_plan'],ttAssignmentEndPlans(),true);$editable=!$legacy&&ttAssignmentIsEditable($a,$retainedStatuses);$generatable=ttAssignmentCanGenerate($a,$retainedStatuses);?><article class="tt-assignment-card"><div class="d-flex justify-content-between"><div><p class="tt-eyebrow mb-1"><?=ttHtml($a['assignment_number'])?></p><h3><?=ttHtml($a['title_snapshot'])?></h3></div><span class="badge tt-status-<?=ttHtml($a['status'])?>"><?=ttHtml(ucwords(str_replace('_',' ',$a['status'])))?></span></div><dl class="tt-compact-dl"><dt>Pattern</dt><dd><?=ttHtml($patterns[$a['operating_pattern']]??$a['operating_pattern'])?></dd><dt>Crew</dt><dd><?=ttHtml($a['crew_name']?:'Unassigned')?></dd><dt>Base</dt><dd><?=ttHtml($a['base_name']?:'Not selected')?></dd><dt>Locomotives</dt><dd><?=(int)$a['locomotive_count']?></dd><dt>Starting cars</dt><dd><?=(int)$a['starting_car_count']?></dd><dt>Planned moves</dt><dd><?=(int)($a['planned_move_count']??0)?></dd></dl><?php if($legacy):?><div class="alert alert-secondary py-2">Legacy inheritance or end-plan settings are preserved read-only and deferred to a future focused update.</div><?php endif;?><div class="d-flex flex-wrap gap-2">
<?php if($editable):?><a class="btn btn-sm btn-outline-secondary" href="assignment_edit.php?id=<?=(int)$a['id']?>">Edit Assignment</a><?php endif;?>
<?php if(!$a['switch_list_id']&&$generatable):?><a class="btn btn-sm btn-primary" href="generate.php?assignment_id=<?=(int)$a['id']?>">Generate Switch List</a><?php elseif($a['switch_list_status']==='draft'):?><a class="btn btn-sm btn-primary" href="work_order.php?id=<?=(int)$a['switch_list_id']?>">Review Switch List</a><?php if($generatable):?><a class="btn btn-sm btn-outline-primary" href="generate.php?assignment_id=<?=(int)$a['id']?>">Regenerate Switch List</a><?php endif;?><?php elseif($a['switch_list_id']):?><a class="btn btn-sm btn-primary" href="work_order.php?id=<?=(int)$a['switch_list_id']?>">View Switch List</a><?php endif;?>
<?php if($editable):?><form method="post" action="assignment_delete.php" onsubmit="return confirm('Delete <?=ttHtml($a['assignment_number'])?>? This removes only safe draft data.')"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="assignment_id" value="<?=(int)$a['id']?>"><button class="btn btn-sm btn-outline-danger">Delete Assignment</button></form><?php endif;?></div></article><?php endforeach;?></div>
<?php if(ttOperatingSessionIsEditable((string)$session['status'])):?><div class="card"><div class="card-header"><h2 class="h4 mb-0">Create Assignment</h2></div><div class="card-body"><form method="post" class="row g-3 tt-assignment-form"><input type="hidden" name="csrf_token" value="<?=ttHtml(ttOperationsCsrfToken())?>"><input type="hidden" name="session_id" value="<?=$sessionId?>"><input type="hidden" name="action" value="add_assignment">
<div class="col-md-6"><label class="form-label">Job Title</label><select class="form-select" name="job_template_id" required><option value="">Choose…</option><?php foreach($jobs as$job):?><option value="<?=(int)$job['id']?>" data-pattern="<?=ttHtml($job['job_type'])?>"><?=ttHtml($job['job_name'])?></option><?php endforeach;?></select></div>
<div class="col-md-6"><label class="form-label">Start Method</label><select class="form-select" name="start_method"><option value="locomotives_only">Locomotives only</option><option value="prepared_cut">Travel light to pick up a prepared cut</option><option value="coupled_selected">Already coupled to selected cars</option><option value="manual">Select starting cars manually</option><option value="auto_build">Auto-build</option></select></div>
<div class="col-md-6 tt-field-base"><label class="form-label">Operating Base</label><select class="form-select" name="operating_base_industry_id"><option value="">Choose…</option><?php foreach($industries as$i):?><option value="<?=(int)$i['id']?>"><?=ttHtml($i['industry_name'])?></option><?php endforeach;?></select></div><div class="col-md-6 tt-field-track"><label class="form-label">Starting Track</label><input class="form-control" name="starting_track" maxlength="120"></div>
<div class="col-12 tt-field-cut" hidden><label class="form-label">Prepared Cut</label><select class="form-select" name="prepared_cut_id"><option value="">Choose…</option><?php foreach($cuts as$c):?><option value="<?=(int)$c['id']?>" data-summary="<?=ttHtml($c['industry_name'].($c['current_track']!==''?' / '.$c['current_track']:'').' · '.$c['car_count'].' cars')?>"><?=ttHtml($c['cut_number'].' — '.$c['name'])?></option><?php endforeach;?></select><div class="form-text tt-cut-summary"></div></div>
<div class="col-12 tt-field-locos"><label class="form-label">Locomotives</label><div class="tt-check-grid"><?php foreach($locomotives as$l):?><label><input type="checkbox" name="locomotive_ids[]" value="<?=(int)$l['id']?>"> <?=ttHtml(trim($l['reporting_marks'].' '.$l['road_number'].' '.$l['road_name']))?></label><?php endforeach;?></div></div>
<div class="col-12 tt-field-cars" hidden><label class="form-label">Starting Cars</label><div class="tt-check-grid"><?php foreach($startingCars as$c):?><label data-location-id="<?=(int)$c['current_industry_id']?>"><input type="checkbox" name="starting_car_ids[]" value="<?=(int)$c['id']?>"> <?=ttHtml(trim($c['reporting_marks'].' '.$c['road_number'].' '.$c['equipment_type'].' — '.$c['industry_name'].($c['current_track']!==''?' / '.$c['current_track']:'')))?></label><?php endforeach;?></div><div class="form-text">Cars are limited to the selected Operating Base; coupled cars must also match Starting Track.</div></div>
<div class="col-md-6"><label class="form-label">Crew</label><input class="form-control" name="crew_name" maxlength="120" placeholder="May be assigned later"></div>
<div class="col-12"><details class="tt-advanced"><summary class="btn btn-sm btn-outline-secondary">Advanced Options</summary><div class="row g-3 mt-1"><div class="col-md-6"><label class="form-label">Operating Pattern Override</label><select class="form-select" name="operating_pattern"><option value="">Use Job Title default</option><?php foreach($patterns as$v=>$label):?><option value="<?=ttHtml($v)?>"><?=ttHtml($label)?></option><?php endforeach;?></select></div><div class="col-md-3 tt-field-prepared-switch-limit" hidden><label class="form-label">Prepared Cut Cars to Switch</label><input class="form-control" type="number" name="prepared_cut_car_count" min="0" max="100" value="10"><div class="form-text">Only this many prepared-cut cars may receive Spot moves.</div></div><div class="col-md-3"><label class="form-label"><span class="tt-requested-label">Cars To Switch (maximum)</span></label><input class="form-control" type="number" name="requested_car_count" min="0" max="100" value="10"><div class="form-text tt-prepared-pickup-help" hidden>This limit applies only to additional pickups at configured Operating Areas.</div></div><div class="col-md-3"><label class="form-label">Difficulty</label><select class="form-select" name="difficulty"><option>easy</option><option selected>medium</option><option>hard</option></select></div><div class="col-md-6"><label class="form-label">End Plan</label><select class="form-select" name="end_plan"><option value="return_origin">Return to origin and tie down</option><option value="terminate_elsewhere">Terminate at another location</option></select></div><div class="col-md-3 tt-field-end"><label class="form-label">End Location <span class="text-muted">(required for Terminate elsewhere)</span></label><select class="form-select" name="end_industry_id"><option value="">As planned</option><?php foreach($industries as$i):?><option value="<?=(int)$i['id']?>"><?=ttHtml($i['industry_name'])?></option><?php endforeach;?></select></div><div class="col-md-3 tt-field-end"><label class="form-label">End Track</label><input class="form-control" name="end_track" maxlength="120"></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="2"></textarea></div></div></details></div><div><button class="btn btn-primary">Add Assignment</button></div></form></div></div>
<?php else:?><div class="alert alert-secondary">This operating session is frozen. Assignments are read-only.</div><?php endif;?></section></div><script src="../assets/js/assignment-form.js"></script><?php include '../includes/footer.php';?>
