CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
password_hash VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE railroads (
id INT AUTO_INCREMENT PRIMARY KEY,
user_id INT NOT NULL,
name VARCHAR(255) NOT NULL
);

CREATE TABLE equipment (
id INT AUTO_INCREMENT PRIMARY KEY,
railroad_id INT NOT NULL,
reporting_marks VARCHAR(20) NOT NULL,
road_number VARCHAR(20) NOT NULL
);
