<?php
session_start();require_once '../config/database.php';require_once '../operations/lib.php';if(!isset($_SESSION['user_id'])){header('Location: ../login.php');exit;}$railroad=ttOperationsRailroad($pdo,(int)$_SESSION['user_id']);$types=ttJobTypes();$search=substr(trim((string)($_GET['search']??'')),0,120);$params=[(int)$railroad['id']];$where='railroad_id=?';if($search!==''){$where.=' AND (job_name LIKE ? OR job_type LIKE ? OR description LIKE ?)';$like='%'.$search.'%';array_push($params,$like,$like,$like);}$stmt=$pdo->prepare("SELECT * FROM jobs WHERE $where ORDER BY active DESC,job_name");$stmt->execute($params);$jobs=$stmt->fetchAll(PDO::FETCH_ASSOC);
?>
<?php include '../includes/header.php';?><title>Operations Job Titles</title><link rel="stylesheet" href="../assets/css/list_v2.css"></head><body><?php include '../includes/navbar.php';?>
<div class="container mt-4"><div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4"><div><p class="text-uppercase text-muted small mb-1">Operations</p><h1 class="mb-1">Job Titles</h1><p class="text-muted mb-0">Reusable names and default patterns. Session equipment is assigned separately.</p></div><a class="btn btn-primary" href="add.php">Add Job Title</a></div>
<form class="row g-2 mb-3" method="get"><div class="col-sm-8 col-md-5"><input class="form-control" name="search" value="<?=ttHtml($search)?>" placeholder="Search job titles"></div><div class="col-auto"><button class="btn btn-outline-primary">Search</button></div></form>
<div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Job Title</th><th>Default Pattern</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach($jobs as $job):$label=$types[$job['job_type']]??($job['custom_job_type']?:ucwords(str_replace('_',' ',$job['job_type'])));?><tr><td><a href="view.php?id=<?=(int)$job['id']?>"><strong><?=ttHtml($job['job_name'])?></strong></a><div class="small text-muted text-truncate" style="max-width:500px"><?=ttHtml($job['description'])?></div></td><td><?=ttHtml($label)?></td><td><span class="badge <?=$job['active']?'bg-success':'bg-secondary'?>"><?=$job['active']?'Active':'Inactive'?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="edit.php?id=<?=(int)$job['id']?>">Edit</a></td></tr><?php endforeach;?>
<?php if(!$jobs):?><tr><td colspan="4" class="text-center text-muted py-5">No job titles found.</td></tr><?php endif;?></tbody></table></div></div></div><?php include '../includes/footer.php';?>
